<?xml version="1.0"?>

<robot name="openmv_cam" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="mass" value="0.01" /> <!-- kg -->
    <xacro:property name="image_height" value="128" />
    <xacro:property name="horizontal_fov" value="2.007128639793479" />  <!-- 115 deg -->
    <xacro:property name="vertical_fov" value="1.5009831567151235" /> <!-- 86 deg -->
    <xacro:property name="image_width" value="${image_height * horizontal_fov / vertical_fov}" />
    <xacro:property name="namespace" value="" />
    <xacro:property name="frame_rate" value="10" />
    <xacro:property name="image_format" value="R8G8B8" />  <!-- L8 -->
    <xacro:property name="min_distance" value="0.01" />
    <xacro:property name="max_distance" value="100" />
    <xacro:property name="enable_visual" value="true" />
    <xacro:property name="visualize_fov" value="true" />
    <xacro:property name="enable_collision" value="true" />
    <xacro:property name="noise_mean" value="0.0" />
    <xacro:property name="noise_stddev" value="0.0" />
    <xacro:property name="camera_suffix" value="main" />
    <xacro:property name="parent_link" value="base_link" />

    <xacro:include filename="openmv_cam_macro.xacro" />

    <link name="base_link"></link>

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_link_inertia" />
    </joint>

    <link name="base_link_inertia">
      <inertial>
        <mass value="${mass}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </inertial>
    </link>

    <xacro:openmv_cam_macro
      namespace="${namespace}"
      parent_link="${parent_link}"
      camera_suffix="${camera_suffix}"
      frame_rate="${frame_rate}"
      horizontal_fov="${horizontal_fov}"
      image_width="${image_width}"
      image_height="${image_height}"
      image_format="${image_format}"
      min_distance="${min_distance}"
      max_distance="${max_distance}"
      visualize_fov="${visualize_fov}"
      noise_mean="${noise_mean}"
      noise_stddev="${noise_stddev}"
      enable_collision="${enable_collision}"
      enable_visual="${enable_visual}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:openmv_cam_macro>

</robot>